title: "Annamalai Muthupalaniappan"
logo: "/Media/Anna_DP_Circle.png"
description: >
  <b>Roboticist | Robotics Engineer | Motion Planning | Manipulation | Simulation | Path Planning | Controls | Mechatronics | Localization and Mapping | Mobile Robots</b><br><br>
  <b>Contact Information:</b><br>
  ðŸ“§ <a href="mailto:annamala@udel.edu">annamala@udel.edu</a><br>
  ðŸ“ž <b>(+1) 667-368-8895</b><br>
  ðŸ”— <a href="https://www.linkedin.com/in/anna2malai-m" target="_blank">LinkedIn</a> |
show_downloads: false
theme: jekyll-theme-minimal